name: hello world workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Hello World
        run: echo "Hello, GitHub Actions is working!"
