name: "multi event pipline/ workflow"

on:
    push:
        branches:
            - master

jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on the master push"
              run: echo "Running on the mster push"